[features]
seeds = false
skip-lint = false
[programs.localnet]
crowdfunding = "4GTfnVe1TX6EyTaVYrqX1x3msYbVto4f6TSFywYLDYmn"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "./id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
